name: pokemon
description: pokemon.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  bloc: ^8.1.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  dio: ^4.0.6
  retrofit: ^3.3.1
  injectable: ^2.1.0
  get_it: ^7.2.0
  freezed_annotation: ^2.0.3
  no_context_navigation: ^2.1.2
  cached_network_image: ^3.2.3

  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^1.0.0
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  retrofit_generator: ^4.2.0
  injectable_generator: ^2.1.3
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true
  generate: true